namespace: 'lacrif'
name: 'itop'
version: '0.1.0'
readme: 'README.md'
authors:
  - 'lacrif'
description: 'Ansible collection for iTop, the open source IT service management software.'
license_file: 'LICENCE'
tags:
  - itop

repository: 'https://github.com/lacrif/ansible-collection-itop'
documentation: 'https://github.com/lacrif/ansible-collection-itop'
homepage: 'https://github.com/lacrif/ansible-collection-itop'
issues: 'https://github.com/lacrif/ansible-collection-itop/issues'
